### ISSUE TITLE
Style scrollbar code blocks

### ISSUE THREAD

**Issue by peterpeterparker** [junobuild/docs#115]
Particularly on the landing page, scrollbar X might appears in the code blocks if the content is larger than the width. Those scrollbars are currently not styled which looks a bit ugly given the strong border and shadow.

**Comment by JeffreyJoel** [comment]
Hi @peterpeterparker can I raise a PR for this?

**Comment by peterpeterparker** [comment]
Sure, go for it Jeffrey 👍

**Comment by JeffreyJoel** [comment]
![image](https://github.com/junobuild/docs/assets/72028836/c879f215-3e95-4566-8330-701d686f9768)

@peterpeterparker is this better?

**Comment by peterpeterparker** [comment]
Oh yeah that's cool @JeffreyJoel! 👍
