### ISSUE TITLE
Minimal Docker version on Macbook for local dev

### ISSUE THREAD

**Issue by peterpeterparker** [junobuild/docs#136]
Particularly for MacBooks with M processors, it is important to use Docker Desktop v4.25.0 or more recent versions, ideally the latest one.

This should be documented in the [Before You Begin](https://juno.build/docs/guides/local-development#before-you-begin) chapter of the "Local Development" section.

**Comment by MukulKolpe** [comment]
Hey @peterpeterparker, can I work on this one?

**Comment by peterpeterparker** [comment]
Sure go for it 👍
