### ISSUE TITLE
Reaching out to add The Great Crypto VC Job Board to Juno's Showcase

### ISSUE THREAD

**Issue by ishaaqziyan** [junobuild/docs#174]
Gm!
I am reaching out to the Juno team to add my new side project developed via Juno, per suggestions by @peterpeterparker 
It's a simple website combining the top 30 crypto VC job portals to improve job hunting efficiency for the average web3 job seeker.
The repo is available [here](https://github.com/ishaaqziyan/VC-Job-Board) and the live website is available [here](https://hcf2z-5yaaa-aaaal-ajxja-cai.icp0.io/).
Wagmi!
Ishaaq

**Comment by ishaaqziyan** [comment]
Title: The Great Crypto VC Job Board
Description: A simple website combining the top 30 crypto VC job portals to improve job hunting efficiency for the average web3 job seeker.
Image: ![image](https://github.com/user-attachments/assets/2dfd18d8-7457-435b-b593-fa0d08cdb289)
URL: https://hcf2z-5yaaa-aaaal-ajxja-cai.icp0.io/
Source code URL: https://github.com/ishaaqziyan/VC-Job-Board
Twitter/X handle: https://x.com/IshaaqZiyan

**Comment by peterpeterparker** [comment]
Thanks! You are live.

https://juno.build/showcase

Note that the order of the showcase is randomized at each build (excep my projects that are always listed at the end).
