### ISSUE TITLE
filter parameter missing in listDocs

### ISSUE THREAD

**Issue by bytesun** [junobuild/docs#218]
In document https://juno.build/docs/build/datastore,
I think "filter" as listDocs's parameter is missing 
and "matcher" doesn't look like it's the parameter of listDocs, it should be under filter as:

```
await listDocs({
      collection: "xxx",
      filter: {  
        matcher: {
          createdAt: {
            matcher: "greaterThan",
            timestamp: BigInt(new Date().getTime()* 1_000_000),
          }
        }, 
```

**Comment by peterpeterparker** [comment]
Thanks! It should be better now, can you double check?
