### ISSUE TITLE
Documents listDocs return

### ISSUE THREAD

**Issue by peterpeterparker** [junobuild/docs#86]
[listDocs](https://juno.build/docs/build/datastore#list-documents) and [listAssets](https://juno.build/docs/build/storage#list-assets) returns various information which are currently not documented - i.e. the details of the return of the function is not document and it would be interested to document it.

```
export interface ListResults<T> {
  // The data - e.g. the documents or assets depending which list was called
  items: T[];
  // The numbers of items - basically items.length
  items_length: bigint;
  // If query is paginated, at what page (starting from 0) the items find place
  items_page?: bigint;
  // The total numbers of matching results
  matches_length: bigint;
  // If query is paginated, the total number (starting from 0) of pages
  matches_pages?: bigint;
}
```

**Comment by Codensity30** [comment]
@peterpeterparker I would like to work on this. Is the interface provided above, the same for `listDocs` and `listAssets`, if not can you please guide me on where to look for it?
Also, if we have any contributing guidelines let me know.

**Comment by peterpeterparker** [comment]
The interface is the same for both `listDocs` and `listAssets`, that is why the interface uses the term `items` and `matches`. When you query `listDocs` you get documents and `listAssets` well, assets.

`listDocs` is used with the Datastore (super simple keypair database) and `listAssets` with the Storage (a store to save files like images etc.).

The interface can be documented in the related pages of the documentation: [listDocs](https://juno.build/docs/build/datastore#list-documents) and [listAssets](https://juno.build/docs/build/storage#list-assets)

There is no particular guidelines.

Let me know if you have more question.

PS: are you participating to the "30 days of web3"?

**Comment by bobeu** [comment]
@peterpeterparker I'd like to work on this if open

**Comment by peterpeterparker** [comment]
Thanks @bobeu but, @Codensity30 already pinged me about this issue earlier today and will take care of it if I get it right.

**Comment by bobeu** [comment]
> Thanks @bobeu but, @Codensity30 already pinged me about this issue earlier today and will take care of it if I get it right.

Just saw that now. I've been on this page for about 2 hours checking the docs. I haven't refreshed it until now I saw his proposal. That's okay. BTW, shoutout to the team for doing awesome jobs.

**Comment by Codensity30** [comment]
@peterpeterparker Yes, I'm participating in "30 days of web3", to be honest, I'm new to the web3 field, hence I've chosen this issue cause it's related to docs.
Thanks for clearing my doubts will surely ask if I get any queries.

**Comment by Codensity30** [comment]
@peterpeterparker Please check this, if the format is correct - 
![image](https://github.com/junobuild/docs/assets/129579058/f73896a3-836d-4950-ac6c-c8badd403329)
or, we can use the format of [Wagmi](https://wagmi.sh/react/api/hooks/useReadContracts#return-type) docs but this will not be consistent with the current `Juno` docs format.

**Comment by peterpeterparker** [comment]
My original idea was "just" having a list or table but, I actually like your idea, it's a cool approach 👍. Sure works for me.

**Comment by Codensity30** [comment]
Okay, will use the same format for `listAssets` too. And I think removing `export interface`, keyword from the code and keeping only the object will make it more clear for users to understand.

**Comment by peterpeterparker** [comment]
Sounds good!
